In [7]:
import torch

# 创建一个 3x3 的随机张量
a = torch.randn(3, 3)
print(a)
# 输出:
# tensor([[-1.0813, -0.8619, 0.7105],
# [ 0.0935, 0.1380, 2.2112],
# [-0.3409, -0.9828, 0.0289]])

# 获取下三角矩阵
tril_a = torch.tril(a)
print(tril_a)

# 获取上三角矩阵
attention_mask = ~torch.tril(torch.ones((3,3), dtype=torch.bool))
print(attention_mask)

attn_mask = torch.triu(torch.ones((3,3)), diagonal=1).bool()
print(attn_mask)

tensor([[-1.1372,  0.4301,  0.9642],
        [ 1.0892, -1.1582, -0.2806],
        [-0.5574,  0.7754, -2.1844]])
tensor([[-1.1372,  0.0000,  0.0000],
        [ 1.0892, -1.1582,  0.0000],
        [-0.5574,  0.7754, -2.1844]])
tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])
tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])


In [9]:
import torch
import torch.nn as nn

# 输入张量
input_tensor = torch.randn(2, 3, 4)  # (batch_size, sequence_length, feature_size)

# 创建 LayerNorm 层
layer_norm = nn.LayerNorm(normalized_shape=4)  # 对最后一个维度进行归一化

# 应用 LayerNorm
normalized_tensor = layer_norm(input_tensor)
print(normalized_tensor.shape)  # 输出形状应与输入相同: (2, 3, 4)


torch.Size([2, 3, 4])


In [27]:
def data_process():
    data = pd.read_csv('./data/MovieLens-1m/ratings.dat',
                    sep='::',
                    names=['user_id', 'movie_id', 'rating', 'timestamp'],
                    engine='python')
    
    user_num = 0
    item_num = 0
    User = defaultdict(list)
    # 只划分训练集和测试集，不做验证集，但是训练过程中，一段时间会对测试集进行评测（其实就相当于验证集了哈哈哈）
    user_train = {}
    user_test = {}
    for index, row in data.iterrows():
        if index % 100000 == 0:
            print("已处理 %d 条数据" % index)
        user = int(row['user_id'])
        item = int(row['movie_id'])

        # 因为user_id和movie_id是连续的整数编号，并从1开始，所以可以用最大值来确定总数
        user_num = max(user, user_num)
        item_num = max(item, item_num)

        rating = int(row['rating'])
        timestamp = int(row['timestamp'])
        User[user].append([timestamp, item, rating])
        
    for userid in User.keys():
        # 根据时间轴排序，构建每个用户的历史交互序列
        User[userid].sort(key=lambda x: x[0])
    print(User[5])

    for userid in User.keys():
        if len(User[userid]) < 4:
            continue
        user_train[userid] = []
        for i_seq in range(len(User[userid])-1):
            user_train[userid].append(User[userid][i_seq][1])
        user_test[userid] = []
        user_test[userid].append(User[userid][-1][1])
    return [user_train, user_test, user_num, item_num]

In [28]:
import pandas as pd
from collections import defaultdict

[user_train, user_test, user_num, item_num] = data_process()

已处理 0 条数据
已处理 100000 条数据
已处理 200000 条数据
已处理 300000 条数据
已处理 400000 条数据
已处理 500000 条数据
已处理 600000 条数据
已处理 700000 条数据
已处理 800000 条数据
已处理 900000 条数据
已处理 1000000 条数据
[[978241072, 2717, 1], [978241072, 908, 4], [978241072, 919, 4], [978241112, 1250, 5], [978241112, 356, 1], [978241390, 2858, 4], [978241390, 1127, 1], [978241390, 2188, 1], [978241434, 2683, 3], [978241434, 3051, 2], [978241556, 2997, 5], [978241981, 2770, 4], [978241981, 2355, 5], [978241981, 2908, 4], [978241981, 3786, 3], [978242016, 3016, 4], [978242080, 2759, 3], [978242080, 1093, 2], [978242323, 2599, 5], [978242323, 3113, 1], [978242323, 3408, 3], [978242541, 2428, 3], [978242541, 2959, 4], [978242541, 3409, 3], [978242607, 2333, 4], [978242607, 2716, 3], [978242607, 2580, 4], [978242607, 2607, 2], [978242640, 2318, 4], [978242679, 2390, 4], [978242740, 913, 5], [978242788, 2723, 4], [978242788, 2734, 2], [978242847, 968, 3], [978242934, 299, 3], [978242934, 2013, 3], [978242934, 24, 1], [978242977, 2560, 4], [978242977

In [ ]:
user_test[2]

In [ ]:
print(user_num, item_num)

6040 3952


In [ ]:
import random

random.seed(42)
uids = list(user_train.keys())
random.shuffle(uids)
print(uids)

uids = list(user_train.keys())
random.shuffle(uids)
print(uids)

uids = list(user_train.keys())
random.shuffle(uids)
print(uids)

uids = list(user_train.keys())
random.shuffle(uids)
print(uids)

uids = list(user_train.keys())
random.shuffle(uids)
print(uids)

[783, 3558, 4682, 3341, 538, 4358, 273, 3913, 1448, 2358, 2704, 1532, 1008, 3444, 4974, 3918, 3938, 2459, 3490, 5898, 4798, 5377, 4773, 5173, 2679, 190, 3824, 4891, 977, 1420, 4754, 5878, 4277, 1802, 1683, 4696, 1548, 85, 512, 5017, 4354, 2032, 4269, 3498, 4706, 2152, 76, 3792, 1836, 2602, 387, 3161, 3775, 2498, 3315, 5147, 87, 3555, 2523, 4040, 4122, 1182, 5837, 4726, 5317, 3249, 723, 3702, 5777, 5967, 3009, 5620, 4224, 2552, 214, 4209, 5372, 1028, 1180, 996, 2098, 5396, 4508, 5885, 3591, 1741, 508, 966, 3561, 2716, 4042, 158, 251, 6032, 3447, 1549, 2107, 3991, 328, 3360, 1370, 3189, 280, 5300, 2487, 3266, 4324, 3391, 5258, 2768, 406, 2312, 2545, 290, 4114, 4267, 2126, 1513, 5730, 1580, 3800, 4192, 3650, 759, 396, 2004, 4249, 1203, 1340, 1469, 4225, 341, 5759, 2833, 249, 4916, 3208, 2919, 123, 4927, 3305, 1492, 2375, 4863, 5349, 5367, 4098, 2790, 5646, 3972, 2259, 5842, 1859, 5975, 724, 1820, 5041, 5424, 2412, 3488, 519, 3818, 5028, 825, 4082, 5457, 1977, 163, 2934, 4530, 1788, 152, 5

In [3]:
user_train[1]

[3186,
 1270,
 1721,
 1022,
 2340,
 1836,
 3408,
 2804,
 1207,
 1193,
 720,
 260,
 919,
 608,
 2692,
 1961,
 2028,
 3105,
 938,
 1035,
 1962,
 2018,
 150,
 1028,
 1097,
 914,
 1287,
 2797,
 2762,
 1246,
 661,
 2918,
 531,
 3114,
 2791,
 2321,
 1029,
 1197,
 594,
 2398,
 1545,
 527,
 595,
 2687,
 745,
 588,
 1,
 2355,
 2294,
 783,
 1566]

In [10]:
import numpy as np
import random

random.seed(42)
np.random.seed(42)

print(np.random.randint(2e9))
print(np.random.randint(2e9))
print(np.random.randint(2e9))


1608637542
1273642419
1935803228


In [ ]:
import numpy as np
import random

random.seed(42)
np.random.seed(42)

print(np.random.randint(2e9))
print(np.random.randint(2e9))
print(np.random.randint(2e9))

1914837113
669991378
429389014


In [ ]:
import random
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from collections import defaultdict
from multiprocessing import Process, Queue

random.seed(42)

# Embedding Layer, 直接使用PyTorch的Embedding实现：torch.nn.Embedding

# self-attention，直接使用PyTorch的MultiheadAttention实现：torch.nn.MultiheadAttention

# FFN，PointWisteFeedForward module
class PointWiseFeedForward(nn.Module):
    def __init__(self, hidden_dim, dropout_rate=0.2, dropout_extra=False):
        super().__init__()
        # 论文里面两个W矩阵都是d*d
        self.fc1 = torch.nn.Linear(hidden_dim, hidden_dim)   
        self.fc2 = torch.nn.Linear(hidden_dim, hidden_dim)
        # 偏置项，都是d维向量
        self.b1 = torch.nn.Parameter(torch.zeros(hidden_dim))
        self.b2 = torch.nn.Parameter(torch.zeros(hidden_dim))
        # 论文公式里只有第一层用了激活函数
        self.activation = torch.nn.ReLU()

        self.dropout_extra = dropout_extra
        self.dropout1 = torch.nn.Dropout(p=dropout_rate)
        self.dropout2 = torch.nn.Dropout(p=dropout_rate)
    
    def forward(self, x):
        # x: [B, L, d]， L是序列长度，d是隐藏层维度
        if self.dropout_extra:
            out = self.fc1(x) + self.b1  # [batch_size, seq_len, embed_dim]
            out = self.activation(out)    # [batch_size, seq_len, embed_dim]
            out = self.dropout1(out)      # [batch_size, seq_len, embed_dim]
            out = self.fc2(out) + self.b2 # [batch_size, seq_len, embed_dim]
            out = self.dropout2(out)      # [batch_size, seq_len, embed_dim]
        else:
            out = self.fc1(x) + self.b1  # [batch_size, seq_len, embed_dim]
            out = self.activation(out)    # [batch_size, seq_len, embed_dim]
            out = self.fc2(out) + self.b2 # [batch_size, seq_len, embed_dim]
        return out

# LayerNorm module，直接使用PyTorch的LayerNorm实现：torch.nn.LayerNorm
    
# SASRec，运行前请设定好超参数
class SASRec(nn.Module):
    def __init__(self, user_num, item_num):
        super().__init__()
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.norm_type = "pre"  # "pre" or "post"，使用pre-norm还是post-norm
        self.maxlen = 200      # 序列最大长度，即论文中的n，对于MovieLens-1M，最大序列长度n被设置为200
        self.embed_dim = 50  # 嵌入维度，即论文中的d（50） 
        self.num_blocks = 2 # 注意力模块的堆叠层数，即论文中为2
        self.num_heads = 1  # 多头注意力机制的头数，论文中只是用了1个头的attention
        self.learning_rate = 0.001 # 学习率论文中设置为0.001
        self.l2_emb = 0.0    # L2正则化系数 
        self.batch_size = 128 # 批大小为128

        self.dropout_rate = 0.2 # 由于MovieLens-1M数据集的稀疏性，关闭神经元的丢失率为0.2
        self.dropout_extra = False # 有些复现SASRec的代码有额外的dropout层，这里作为可选项

        # 论文实现细节：优化器是ADAM优化器

        self.user_num = user_num
        self.item_num = item_num

        # +1是因为需要额外的索引0来表示padding位置
        self.item_emb = torch.nn.Embedding(self.item_num+1, self.embed_dim, padding_idx=0)
        self.pos_emb = torch.nn.Embedding(self.maxlen+1, self.embed_dim, padding_idx=0)
        self.emb_dropout = torch.nn.Dropout(p=self.dropout_rate)

        self.attention_layers = torch.nn.ModuleList()
        self.attention_layernorms = torch.nn.ModuleList()
        self.forward_layers = torch.nn.ModuleList()
        self.forward_layernorms = torch.nn.ModuleList()

        # self.pos_sigmoid = torch.nn.Sigmoid()
        # self.neg_sigmoid = torch.nn.Sigmoid()

        # 因为想对比pre-norm和post-norm的效果，所以不直接做好层的顺序，只累计层的数量
        for _ in range(self.num_blocks):
            # batch_first=True  # 关键参数, 让输入保持 [batch, seq, hidden]
            self.attention_layers.append(
                torch.nn.MultiheadAttention(self.embed_dim, self.num_heads, self.dropout_rate, batch_first=True)
            )

            self.forward_layers.append(
                PointWiseFeedForward(self.embed_dim, self.dropout_rate, self.dropout_extra)
            )

            self.attention_layernorms.append(
                torch.nn.LayerNorm(self.embed_dim, eps=1e-8)
            )

            self.forward_layernorms.append(
                torch.nn.LayerNorm(self.embed_dim, eps=1e-8)
            )
    
    # 根据self.norm_type选择前归一化还是后归一化
    def log2feats(self, log_seqs):
        # log_seqs为输入序列，形状： [batch_size, seq_len]
        # 将序列转成embedding表示
        seqs = self.item_emb(torch.LongTensor(log_seqs).to(self.device)) # 输出形状: [batch_size, seq_len, embed_dim]

        # 缩放嵌入向量，乘以嵌入维度的平方根，论文没提，但这是Transformer中的常见做法
        seqs *= self.item_emb.embedding_dim ** 0.5  # 目的是在注意力计算前保持数值稳定性

        # 3. 创建位置编码
        # np.tile用于将数组沿指定的维度重复，从而生成一个新的数组。它非常适合在需要扩展或重复数据时使用
        position = np.tile(np.arange(1, log_seqs.shape[1] + 1), [log_seqs.shape[0], 1])  # 形状: [batch_size, seq_len]
        # 生成位置索引矩阵，从1开始到序列长度
        # 例如: 如果seq_len=4, batch_size=2（即log_seqs.shape[0]=2） → [[1,2,3,4], [1,2,3,4]]

        # 处理padding位置
        poss *= (log_seqs != 0)
        # 将padding位置（值为0）的位置编码设为0
        # 避免对padding位置进行位置编码

        # 添加位置编码
        seqs += self.pos_emb(torch.LongTensor(poss).to(self.device))
        if self.dropout_extra:
            seqs = self.emb_dropout(seqs)  # 对嵌入向量应用dropout进行正则化
        
        # 创建注意力掩码
        tl = seqs.shape[1]  # 序列长度

        # 创建上三角掩码矩阵，用于实现因果注意力
        # 确保每个位置只能关注到它之前的位置
        attention_mask = ~torch.tril(torch.ones((tl, tl), dtype=torch.bool, device=self.device))
        
        for i in range(len(self.attention_layers)):
            # seqs = torch.transpose(seqs, 0, 1) # 早期的 nn.MultiheadAttention 和 nn.Transformer 默认期望输入形状为 [seq_len, batch_size, hidden_dim]，新版设置batch_first=True后不需要转置
            if self.norm_first == "pre":
                # Pre-Norm
                seqs_norm = self.attention_layernorms[i](seqs)
                mha_outputs, _ = self.attention_layers[i](seqs_norm, seqs_norm, seqs_norm, attn_mask=attention_mask)
                seqs_ = seqs + mha_outputs
                seqs_next = seqs_ + self.forward_layers[i](self.forward_layernorms[i](seqs_))
            else:  
                # Post-Norm
                mha_outputs, _ = self.attention_layers[i](seqs, seqs, seqs, attn_mask=attention_mask)
                seqs_ = self.attention_layernorms[i](seqs + mha_outputs)
                seqs_next = self.forward_layernorms[i](seqs_ + self.forward_layers[i](seqs_))
        
        return seqs_next  # 输出形状: [B, L, d]

    def forward(self, user_ids, log_seqs, pos_seqs, neg_seqs): # for training
        # log_seqs: 用户历史行为序列 [batch_size, seq_len]
        # pos_seqs: 正样本序列（行为序列的下一个item），neg_seqs: 负样本序列

        # 将历史序列转换为特征表示 
        log_feats = self.log2feats(log_seqs) # [batch_size, seq_len, hidden_dim]

        # 获取正负样本的嵌入表示
        pos_embs = self.item_emb(torch.LongTensor(pos_seqs).to(self.dev))  # [batch_size, seq_len, hidden_dim]
        neg_embs = self.item_emb(torch.LongTensor(neg_seqs).to(self.dev))  # [batch_size, seq_len, hidden_dim]

        # 计算匹配分数（内积相似度）
        pos_logits = (log_feats * pos_embs).sum(dim=-1)  # [batch_size, seq_len]
        neg_logits = (log_feats * neg_embs).sum(dim=-1)  # [batch_size, seq_len]
        # pos_pred = self.pos_sigmoid(pos_logits)
        # neg_pred = self.neg_sigmoid(neg_logits)

        # """使用用户ID的改进版本"""
        # log_feats = self.log2feats(log_seqs)
        
        # # 添加用户特定的偏置或变换
        # user_embs = self.user_emb(user_ids)  # [batch_size, hidden_dim]
        # user_aware_feats = log_feats + user_embs.unsqueeze(1)  # 广播到序列长度
        
        # pos_embs = self.item_emb(torch.LongTensor(pos_seqs).to(self.dev))
        # neg_embs = self.item_emb(torch.LongTensor(neg_seqs).to(self.dev))
        
        # pos_logits = (user_aware_feats * pos_embs).sum(dim=-1)
        # neg_logits = (user_aware_feats * neg_embs).sum(dim=-1)
        # pos_pred = self.pos_sigmoid(pos_logits)
        # neg_pred = self.neg_sigmoid(neg_logits)
        
        return pos_logits, neg_logits # pos_pred, neg_pred

    def predict(self, user_ids, log_seqs, item_indices): # for inference
        log_feats = self.log2feats(log_seqs) # user_ids hasn't been used yet

        # 只取最后一个时间步的特征作为用户当前兴趣表示，预测下一个特征，即要推荐的item的特征表示，形状: [batch_size, embed_dim]
        final_feat = log_feats[:, -1, :] 

        # 改进方案: 使用最后N个位置
        # final_feat = log_feats[:, -3:, :].mean(dim=1)  # 最后3个位置平均

        # 获取候选物品的嵌入向量
        item_embs = self.item_emb(torch.LongTensor(item_indices).to(self.dev)) 

        # 计算要推荐的item的特征表示与所有候选物品的匹配分数（内积相似度）
        logits = item_embs.matmul(final_feat.unsqueeze(-1)).squeeze(-1)
        # preds = self.pos_sigmoid(logits)
        return logits

def data_process(file_name):
    data = pd.read_csv('./data/MovieLens-1m/ratings.dat',
                    sep='::',
                    names=['user_id', 'movie_id', 'rating', 'timestamp'],
                    engine='python')
    
    user_num = 0
    item_num = 0
    User = defaultdict(list)
    user_train = {}
    user_valid = {}
    user_test = {}
    for index, row in data.iterrows():
        if index % 100000 == 0:
            print("已处理 %d 条数据" % index)
        user = int(row['user_id'])
        item = int(row['movie_id'])

        # 因为user_id和movie_id是连续的整数编号，并从1开始，所以可以用最大值来确定总数
        user_num = max(user, user_num)
        item_num = max(item, item_num)

        rating = int(row['rating'])
        timestamp = int(row['timestamp'])
        User[user].append([timestamp, item, rating])
        
    for userid in User.keys():
        # 根据时间轴排序，构建每个用户的历史交互序列
        User[userid].sort(key=lambda x: x[0])

    for userid in User.keys():
        if len(User[userid]) < 4:
            continue
        user_train[userid] = []
        for i_seq in range(len(User[userid])-2):
            user_train[userid].append(User[userid][i_seq][1])
        user_valid[userid] = []
        user_valid[userid].append(User[userid][-2][1])
        user_test[userid] = []
        user_test[userid].append(User[userid][-1][1])
    return [user_train, user_valid, user_test, user_num, item_num]

In [19]:
model = SASRec(user_num, item_num)
for name, param in model.named_parameters():
    print(name, param.size())

item_emb.weight torch.Size([3953, 50])
pos_emb.weight torch.Size([201, 50])
attention_layers.0.in_proj_weight torch.Size([150, 50])
attention_layers.0.in_proj_bias torch.Size([150])
attention_layers.0.out_proj.weight torch.Size([50, 50])
attention_layers.0.out_proj.bias torch.Size([50])
attention_layers.1.in_proj_weight torch.Size([150, 50])
attention_layers.1.in_proj_bias torch.Size([150])
attention_layers.1.out_proj.weight torch.Size([50, 50])
attention_layers.1.out_proj.bias torch.Size([50])
attention_layernorms.0.weight torch.Size([50])
attention_layernorms.0.bias torch.Size([50])
attention_layernorms.1.weight torch.Size([50])
attention_layernorms.1.bias torch.Size([50])
forward_layers.0.b1 torch.Size([50])
forward_layers.0.b2 torch.Size([50])
forward_layers.0.fc1.weight torch.Size([50, 50])
forward_layers.0.fc1.bias torch.Size([50])
forward_layers.0.fc2.weight torch.Size([50, 50])
forward_layers.0.fc2.bias torch.Size([50])
forward_layers.1.b1 torch.Size([50])
forward_layers.1.b2 t

In [20]:
# 输入维度100，输出维度50
linear_layer = torch.nn.Linear(100, 50)

# Xavier初始化前
print("初始化前:", linear_layer.weight.mean().item(), linear_layer.weight.std().item())

# 应用Xavier初始化
torch.nn.init.xavier_normal_(linear_layer.weight)

# Xavier初始化后
print("初始化后:", linear_layer.weight.mean().item(), linear_layer.weight.std().item())
# 均值接近0，标准差接近 sqrt(2/(100+50)) ≈ 0.115

初始化前: -0.0004982632817700505 0.057467278093099594
初始化后: -0.000379732548026368 0.11606426537036896


In [40]:
num = [1,2,3,4,5]
num_batch = (len(num)-1)//2 + 1
print(num_batch)
for step in range(num_batch):
    start_idx = step * 2
    end_idx = min((step + 1) * 2, len(num))
    batched_num = num[start_idx:end_idx]
    print(batched_num)

3
[1, 2]
[3, 4]
[5]


In [46]:
user_train = [1,2,3,4]
seq = np.zeros([6], dtype=np.int32)
pos = np.zeros([6], dtype=np.int32)
nxt = user_train[-1]
idx = 6 - 1
cur_user_items = set(user_train)  # 记录当前用户交互过的item
for i in reversed(user_train[:-1]):
    seq[idx] = i
    pos[idx] = nxt
    nxt = i
    idx -= 1
    if idx == -1: 
        break
print(seq)
print(pos)

[0 0 0 1 2 3]
[0 0 0 2 3 4]


In [51]:
users = [1,3,5,6,7,8]
users = random.sample(users, 2)
print(users)

[5, 7]


In [17]:
import torch

item_emb = torch.nn.Embedding(9, 9, padding_idx=0)

print(torch.nn.init.xavier_normal_(item_emb.weight))

item_embs = item_emb(torch.LongTensor([2,4]))  # [101, 1, embed_dim]
print(item_embs.shape)
print(item_embs)

Parameter containing:
tensor([[-0.1374, -0.2645,  0.0555, -0.1691,  0.2462, -0.1987, -0.3349,  0.6560,
         -0.0111],
        [-0.2586,  0.0632,  0.0859,  0.0183, -0.2102,  0.1046, -0.0153, -0.0438,
         -0.0385],
        [-0.0048,  0.3537, -0.2719, -0.0297,  0.1382,  0.5585,  0.6117,  0.5414,
         -0.4990],
        [ 0.3490, -0.0401, -0.5441,  0.3389,  0.1573, -0.1842, -0.1710, -0.3480,
          0.7583],
        [ 0.2546, -0.3490,  0.3460, -0.2735,  0.0872, -0.1168,  0.1734,  0.1354,
          0.3288],
        [-0.3959, -0.0846,  0.2327, -0.1506, -0.1578, -0.0546, -0.4814,  0.1550,
          0.2293],
        [ 0.1112,  0.5440, -0.2313,  0.2719,  0.5214,  0.4106, -0.2252,  0.2887,
          0.2772],
        [-0.3759,  0.0883,  0.2964,  0.3777,  0.1486,  0.1198, -0.4323,  0.1769,
          0.0456],
        [-0.1389,  0.2071,  0.1266, -0.0619, -0.6350, -0.2345, -0.1195, -0.1763,
          0.1893]], requires_grad=True)
torch.Size([2, 9])
tensor([[-0.0048,  0.3537, -0.2719, -0

In [21]:
import numpy as np

print(np.array([-0.6, -0.9, -0.1, -0.7, -0.5]).argsort())
print(np.array([-0.6, -0.9, -0.1, -0.7, -0.5]).argsort().argsort())

[1 3 0 4 2]
[2 0 4 1 3]


In [ ]:
# print([-0.6, -0.9, -0.1, -0.7, -0.5].shape)  # 'list' object has no attribute 'shape'
print(np.array([-0.6, -0.9, -0.1, -0.7, -0.5]).shape)

AttributeError: 'list' object has no attribute 'shape'